console.log(typeof (1.1))
console.log(typeof ("Some String"))
console.log(typeof [1,"2",3])
console.log(typeof (1===1))
console.log(typeof {name:"abs", age:30})
console.log(`typeof undefined : ${typeof (undefined)}`)
console.log(`typeof null : ${typeof (null)}`)
console.log(`typeof Symbol() : ${typeof (foo=Symbol())}`)